## Lab 3
### Daniel Mehta #n01753264

In [2]:
import numpy as np

### 1A)

In [11]:
A = np.array([[2, 3, 0],
              [1, 4, 3],
              [0, 0, 1]])
x1 = np.array([3, -1, 0])

Ax1 = np.dot(A, x1)


print("A * x1 =", Ax1)

A * x1 = [ 3 -1  0]


### 1B)

In [13]:
eigenvalue = Ax1[0] / x1[0]

is_eigenvector = np.allclose(Ax1, eigenvalue * x1)

print("Eigenvalue:", eigenvalue)
print("Is x1 an eigenvector of A?", is_eigenvector)

Eigenvalue: 1.0
Is x1 an eigenvector of A? True


### 2)

In [21]:
A = np.array([[4,2],[1,3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(f'Eigenvalues = {eigenvalues}') 
print(f'Eigenvectors =  \n{eigenvectors}')

Eigenvalues = [5. 2.]
Eigenvectors =  
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### 3)

In [27]:
A = np.array([[3, 2, 2],[2,3,2],[2,2,3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

for i, eigenvalue in enumerate(eigenvalues):
    print(f"Eigenspace for eigenvalue {eigenvalue}:")
    print(eigenvectors[:, i])
    print()

Eigenvalues:
[1. 7. 1.]

Eigenvectors:
[[-0.81649658  0.57735027 -0.09365858]
 [ 0.40824829  0.57735027 -0.65561007]
 [ 0.40824829  0.57735027  0.74926865]]
Eigenspace for eigenvalue 0.9999999999999987:
[-0.81649658  0.40824829  0.40824829]

Eigenspace for eigenvalue 6.999999999999998:
[0.57735027 0.57735027 0.57735027]

Eigenspace for eigenvalue 0.9999999999999998:
[-0.09365858 -0.65561007  0.74926865]

